### PR TITLE
forking entry

### PR DESCRIPTION
**Pull request by mche**
ALL GLORY TO GLORIA!

### CODE REVIEW

**Comment by dohnuts** [comment]
FYI, This PR is a mess of few things:
 * the Global $SIG{CHLD} is reset multiple time for dubious reason ( more like an issue ), and the reaper could be installed once
 * https://github.com/rhuss/schedule-cron/blob/master/lib/Schedule/Cron.pm#L630C30-L630C30 the `&& cfg` in the condition is a "no op" that any smart compiler would report  ( since if (ref($args) eq "HASH")  and then cfg is put in $args )
 * An Override of global no fork with specific fork request.

**Comment by dohnuts** [comment]
This PR has not enough Glory ( see Issue #11 )

Testing :
```sh
git clone https://github.com/rhuss/schedule-cron.git && cd schedule-cron/
git remote add pr1 https://github.com/mche/schedule-cron.git
git fetch pr1
git cherry-pick 124d2e4e27536a43e3383fd29c1b55e98ccb316d
# edit version to ensure testing the right code
-bash-5.2$ git diff | cat
```
```diff
diff --git a/lib/Schedule/Cron.pm b/lib/Schedule/Cron.pm
index f8583a6..fce5d09 100644
--- a/lib/Schedule/Cron.pm
+++ b/lib/Schedule/Cron.pm
@@ -81,7 +81,7 @@ BEGIN {
 }


-$VERSION = "1.05";
+$VERSION = "1.05a";

 our $DEBUG = 0;
 my %STARTEDCHILD = ();
```
Code: 
```perl
use lib './lib';
use Schedule::Cron;
use feature 'say';

sub run_bsd {
  say 'banner in '.$$.'('.$_[0].') said: something';
}

my $cron = new Schedule::Cron(sub {});

$cron->add_entry("* * * * *",\&run_bsd, 'default');

$cron->add_entry("* * * * *",{subroutine => \&run_bsd, arguments => '[ "forked" ]', nofork => 0});
$cron->add_entry("* * * * *",{subroutine => \&run_bsd, arguments => '[ "UNfork" ]', nofork => 1});

# Run scheduler

require Config;
my $vers = `uname -r 2>/dev/null` || $Config::Config{'osvers'} ;
chomp $vers;
my $osname = `uname -s 2>/dev/null` || $Config::Config{'osname'};
chomp $osname;
print "# OS: $osname ($vers)\n";
print "# Perl-Version: $]\n";
print "# Time::ParseDate-Version: ",$Time::ParseDate::VERSION,"\n";
print "# Version: ",$Schedule::Cron::VERSION,"\n";
say 'HELLO i am '.$$;

$cron->run(detach=>0,eval=>1,catch=>1,nofork=>$ARGV[0]);
```

Default to nofork will fork only once:

```
-bash-5.2$ perl report.pl 0
# OS: OpenBSD (7.4)
# Perl-Version: 5.036001
# Time::ParseDate-Version: 2015.103
# Version: 1.05a
HELLO i am 94302
banner in 87831(default) said: something
banner in 94302([ "UNfork" ]) said: something
banner in 58977([ "forked" ]) said: something
banner in 94302(default) said: something
banner in 94302([ "forked" ]) said: something
banner in 94302([ "UNfork" ]) said: something
banner in 94302(default) said: something
```

Default to fork will never ever fork:

```
-bash-5.2$ perl report.pl 1
# OS: OpenBSD (7.4)
# Perl-Version: 5.036001
# Time::ParseDate-Version: 2015.103
# Version: 1.05a
HELLO i am 2690
banner in 2690(default) said: something
banner in 2690([ "forked" ]) said: something
banner in 2690([ "UNfork" ]) said: something
banner in 2690(default) said: something
banner in 2690([ "forked" ]) said: something
banner in 2690([ "UNfork" ]) said: something
```

**Comment by rhuss** [comment]
Disclaime: Although I'm the original author (started this in 2001), I'm not maintaining it anymore. @NicholasBHubbard is the current maintainer (btw, @NicholasBHubbard if you like we could transfer this GitHub repo to your account)

> FYI, This PR is a mess of few things:

I wouldn't call it a mess, it's a valuable contribution with some issues :-)

> * the Global $SIG{CHLD} is reset multiple time for dubious reason ( more like an issue ), and the reaper could be installed once

That's true (although its probably not that harmful)

> * https://github.com/rhuss/schedule-cron/blob/master/lib/Schedule/Cron.pm#L630C30-L630C30 the `&& cfg` in the condition is a "no op" that any smart compiler would report  ( since if (ref($args) eq "HASH")  and then cfg is put in $args )

Correct, but this is not part of the PR but has been added by me long time ago :-), hopefully by accident.

> * An Override of global no fork with specific fork request.

It depends on whether you see the global option as a "default that individual entries can override" or an "override that is valid for all entries despite their respective fork/no fork configuration." Since this is not documented, both could be valid. Of course, one could argue what is more helpful, and I agree that using it as a global default that individual entries can override makes more sense. However, it should be at least documented.

Just my 2 cents; I don't have time to work on this further. But it is still interesting to know that this module is still in use after 23 years :-P

**Comment by NicholasBHubbard** [comment]
I'll take a look at this over the next couple days. I'm not exactly sure what's going on with this PR so I'll have to catch myself up.

I am open to moving this repo to my account as well.

**Comment by rhuss** [comment]
@NicholasBHubbard Cool, then let me move it over to your account ....

**Comment by rhuss** [comment]
@NicholasBHubbard I initiated the transfer, you need to accept the request. Have fun, and thanks for taking care!

**Pull request closed without merging**
