### PR TITLE
Add processname option for setting $0 to constant string

### PR DESCRIPTION
**Pull request by NicholasBHubbard**
This PR adds an option `processname` that can be used to set the process name ($0) to a given string. I added this PR because I did not want the process name to have the `MainLoop - next ...` suffix, but there was no way to disable it. 

Using `processname` overrides `nostatus` and `processprefix`.

Let me know what you think!

### CODE REVIEW

**Review by rhuss — APPROVED** [review]
Thanks for the PR! Amazing that this piece of software is still used after all those years (that was my first open-source project, and I think I started it 23 years ago ...)

I don't actively maintain schedule-cron anymore, but happy to merge in your change (which looks good to me), if this is helpful for you. Not sure about a release though, kind of forgot the mechanics and don't have the spare time to redo it. However, if you feel fancy I can add you as a co-maintainer so that you could drive a release.

**Comment by NicholasBHubbard** [comment]
Schedule::Cron is a fundamental component to my project [yabsm](https://github.com/NicholasBHubbard/yabsm)!

I would be happy to take care of a CPAN release - I am [NHUBBARD](https://metacpan.org/author/NHUBBARD) on CPAN/PAUSE.

**Comment by rhuss** [comment]
oops, I just forgot that I already handed over maintenance of schedule::cron to @realflash some time ago, I'm only a co-maintainer now and can't add other co-maintainers. @realflash would you be able to help @NicholasBHubbard ?

**Comment by NicholasBHubbard** [comment]
Thanks @realflash! I added tests in #10.

**Comment by wbraswell** [comment]
@rhuss will you please add @NicholasBHubbard as a developer on this GitHub repository?
@realflash will you please add @NicholasBHubbard as a co-maintainer on PAUSE/CPAN, and also teach him how your GitHub-to-CPAN release process works?
These changes will increase the "bus factor" of Schedule::Cron, and also help an up-and-coming Perl programmer (Nicholas) become more involved in the Perl release process.
Thanks in advance!

**Comment by rhuss** [comment]
Invited @NicholasBHubbard and @realflash to this repo, sorry for the delay.

**Comment by realflash** [comment]
I've added @NicholasBHubbard as COMAINT on PAUSE as requested. As for release process, I haven't done a release of it. I adopted it to make sure it didn't get lost as I was depending on it. It uses ExtUtils::MakeMaker so I would suggest:

- Run tests
- make clean
- make
- make dist

That should do it.

**Comment by NicholasBHubbard** [comment]
Thanks @realflash! I will get to this soon!

**Pull request merged**
